namespace: mlflow-auth-helm

mlflow:
  replicas: 1
  image:
    repository: ghcr.io/mlflow/mlflow
    tag: v2.12.1
  # Switch to PostgreSQL backend
  backendStoreUri: postgresql://mlflow:mlflow-password@mlflow-auth-postgresql:5443/mlflow
  artifactRoot: /mlflow/artifacts
  containerPort: 5000
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30080

oauth2:
  replicas: 1
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: v7.5.1
  provider: oidc
  clientId: mlflow-client
  clientSecret: W19m2xRJenm4T1jtsxsBJ6h5OAJ8DAyZ
  redirectUrl: http://localhost:4180/oauth2/callback
  emailDomain: "*"
  upstream: http://mlflow-service:5000
  httpAddress: 0.0.0.0:4180
  oidcIssuerUrl: https://login.dev.wazuh.adorsys.team/realms/idp-compentence-center
  cookieSecret: SnWj45SpV3Q5jW5W4RDiYA==
  containerPort: 4180
  service:
    port: 4180
    targetPort: 4180

# PostgreSQL database configuration
postgresql:
  enabled: true
  auth:
    username: mlflow
    password: mlflow-password
    database: mlflow
    # Adding postgres password to avoid the upgrade error
    postgresPassword: postgres-admin-password
  primary:
    persistence:
      enabled: true
      size: 8Gi
    containerPorts:
      postgresql: 5443
    service:
      ports:
        postgresql: 5443
  metrics:
    enabled: false
  containerPorts:
    postgresql: 5443
  service:
    ports:
      postgresql: 5443
