apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mlflow.replicas }}
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: {{ .Values.mlflow.image.repository }}:{{ .Values.mlflow.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install psycopg2-binary && \
              mlflow server \
              --backend-store-uri {{ .Values.mlflow.backendStoreUri | quote }} \
              --default-artifact-root {{ .Values.mlflow.artifactRoot }} \
              --host 0.0.0.0
          ports:
            - containerPort: {{ .Values.mlflow.containerPort }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.mlflow.backendStoreUri | quote }}
            - name: POSTGRES_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: POSTGRES_PORT
              value: "5443"
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
          volumeMounts:
            - mountPath: /mlflow
              name: mlflow-data
      volumes:
        - name: mlflow-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: {{ .Values.mlflow.service.port }}
      targetPort: {{ .Values.mlflow.service.targetPort }}
      nodePort: {{ .Values.mlflow.service.nodePort }}
  type: {{ .Values.mlflow.service.type }}